//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderChange
    {
        public int OrderId { get; set; }
        public int CustomerId { get; set; }
        public System.DateTime OrderDate { get; set; }
        public System.DateTime EventDate { get; set; }
        public string EventKind { get; set; }
        public bool StatusPayment { get; set; }
        public int MorningOrEvening { get; set; }
        public int QuantityInvited { get; set; }
        public Nullable<int> NumBridalChair { get; set; }
        public int OrderSum { get; set; }
        public int AdvancePaymentSum { get; set; }
    
        public virtual Customers Customers { get; set; }
        public virtual Order Order { get; set; }
    }
}
