//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PayMents
    {
        public int OrderId { get; set; }
        public string PaymentCyclistDetails { get; set; }
        public string OrderPaymentCsicleDetails { get; set; }
        public int CustomerId { get; set; }
    
        public virtual Customers Customers { get; set; }
        public virtual Order Order { get; set; }
    }
}
